# Generated by Django 3.2.12 on 2022-03-01 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Name')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('budget', models.IntegerField(default=0, verbose_name='Budget')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='MoneyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryType', models.BooleanField(verbose_name='Expense Or Income')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Name')),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='api.category')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.user')),
            ],
            options={
                'db_table': 'Money Entry',
            },
        ),
    ]
