# Generated by Django 3.2.12 on 2022-03-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moneyentry',
            options={'verbose_name_plural': 'Money Entries'},
        ),
        migrations.AddField(
            model_name='moneyentry',
            name='userId',
            field=models.BigIntegerField(default=2, verbose_name='User Id'),
        ),
    ]
